name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.platform.os}}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows - MSVC, os: windows-latest, shell: 'msys2 {0}', msystem: mingw64, msys-env: mingw-w64-x86_64 }
        build-type: [Release]
        build-static: [ON]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Windows dependencies
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.platform.msystem}}
        install: >-
          ${{matrix.platform.msys-env}}-cmake
          ${{matrix.platform.msys-env}}-openssl
          ${{matrix.platform.msys-env}}-zlib

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DOPENSSL_ROOT_DIR=/${{matrix.platform.msystem}} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_STATIC=${{matrix.build-static}}

    - name: Build
      run: cmake --build build --config ${{matrix.build-type}}

    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C ${{matrix.build-type}}
