name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.platform.os}}

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: macOS,             os: macos-latest,   shell: sh }
        build-type: [Release]
        build-static: [ON]
    steps:
    - uses: actions/checkout@v3

    - name: Setup GNU/Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install \
            libssl-dev ninja-build zlib1g-dev

    - name: Setup macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install \
            cmake ninja openssl zlib
        echo "CMAKE_PREFIX_PATH=$(brew --prefix openssl):$(brew --prefix zlib)" >> $GITHUB_ENV


    - name: Setup Windows dependencies
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.platform.msystem}}
        install: >-
          ${{matrix.platform.msys-env}}-gcc
          ${{matrix.platform.msys-env}}-cmake
          ${{matrix.platform.msys-env}}-ninja
          ${{matrix.platform.msys-env}}-openssl
          ${{matrix.platform.msys-env}}-zlib

    - name: Configure CMake
      run: |
        #export CMAKE_PREFIX_PATH=$(brew --prefix openssl):$(brew --prefix zlib)
        echo $CMAKE_PREFIX_PATH
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_STATIC=${{matrix.build-static}}
        #cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_STATIC=${{matrix.build-static}} -DOPENSSL_ROOT_DIR=$(brew --prefix openssl)
